"""Governed canonical market-data quality pipeline.

Imports expose contracts and pure in-memory functions only. No repository file,
network, broker, or output surface is accessed at import time.
"""

from .contracts import (
    BoundaryConvention,
    CalendarBehavior,
    CalendarPolicy,
    CanonicalBarSchema,
    CanonicalizationPolicy,
    DatasetIdentity,
    DSTAmbiguousPolicy,
    DSTNonexistentPolicy,
    DuplicatePolicy,
    EligibilityDecision,
    EligibilityRequirement,
    EvidenceStatus,
    FieldDifferenceCounts,
    GapPolicy,
    GateFinding,
    GateId,
    GateReport,
    GateResult,
    GateStatus,
    IncompleteBinPolicy,
    PeriodSemantics,
    PriceUnitDeclaration,
    ReconciliationResult,
    ReconciliationTolerance,
    RepairRecord,
    ResamplingPolicy,
    TimestampSemantics,
    ValidationMode,
    VolumeAggregation,
    VolumeMeaning,
    VolumeSemantics,
)
from .eligibility import GuardedExecution, evaluate_eligibility, execute_if_eligible
from .normalization import (
    CanonicalInput,
    CanonicalizationResult,
    canonicalize,
    serialize_canonical_frame,
)
from .quality import QualityEvaluation, evaluate_calendar_coverage, evaluate_quality
from .reconciliation import ReconciliationEvaluation, reconcile_bars
from .resampling import ResamplingError, ResamplingResult, resample_bars


__all__ = [
    "BoundaryConvention",
    "CalendarBehavior",
    "CalendarPolicy",
    "CanonicalBarSchema",
    "CanonicalInput",
    "CanonicalizationPolicy",
    "CanonicalizationResult",
    "DSTAmbiguousPolicy",
    "DSTNonexistentPolicy",
    "DatasetIdentity",
    "DuplicatePolicy",
    "EligibilityDecision",
    "EligibilityRequirement",
    "EvidenceStatus",
    "FieldDifferenceCounts",
    "GapPolicy",
    "GateFinding",
    "GateId",
    "GateReport",
    "GateResult",
    "GateStatus",
    "GuardedExecution",
    "IncompleteBinPolicy",
    "PeriodSemantics",
    "PriceUnitDeclaration",
    "QualityEvaluation",
    "ReconciliationEvaluation",
    "ReconciliationResult",
    "ReconciliationTolerance",
    "RepairRecord",
    "ResamplingError",
    "ResamplingPolicy",
    "ResamplingResult",
    "TimestampSemantics",
    "ValidationMode",
    "VolumeAggregation",
    "VolumeMeaning",
    "VolumeSemantics",
    "canonicalize",
    "evaluate_calendar_coverage",
    "evaluate_eligibility",
    "evaluate_quality",
    "execute_if_eligible",
    "reconcile_bars",
    "resample_bars",
    "serialize_canonical_frame",
]
